# Individual Project 2: Working with NumPy
## Leighann Robinson
### Version 1
#### DS160 SP23

In [1]:
import numpy as np

### Question 1

In [2]:
array1=np.array([[10,20],[30,40]])
array1

array([[10, 20],
       [30, 40]])

In [3]:
# Square every element of the array
a=array1
b=2
a^b

array([[ 8, 22],
       [28, 42]], dtype=int32)

In [4]:
# Add 100 to every element of the array
a=array1
c=100
a+c

array([[110, 120],
       [130, 140]])

In [5]:
# Multiply every element of the array by 5
a=array1
d=5
a*d

array([[ 50, 100],
       [150, 200]])

In [6]:
# Calculate the square root of each element in the array
np.sqrt(a)

array([[3.16227766, 4.47213595],
       [5.47722558, 6.32455532]])

### Question 2

In [7]:
# Create a 3-by-3 array containing integers from 3 to 27 in multiples of 3
array2=np.arange(3,30,3)
array2

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [8]:
# Create a second 3-by-3 array with 9 elements evenly spaced between 10 and 20
array3=np.linspace(10,20,9)
array3

array([10.  , 11.25, 12.5 , 13.75, 15.  , 16.25, 17.5 , 18.75, 20.  ])

In [9]:
# Multiply these arrays together and display the output
array4=array2*array3
array4

array([ 30. ,  67.5, 112.5, 165. , 225. , 292.5, 367.5, 450. , 540. ])

### Question 3 

In [10]:
# Attached to the assignment are five .npy files that contain five values each
## Read these files in and stack them into a unified dataset 
### This would be a 5-by-5 NumPy array 

In [11]:
import numpy as np
p1=np.load('process1.npy')
p2=np.load('process2.npy')
p3=np.load('process3.npy')
p4=np.load('process4.npy')
p5=np.load('process5.npy')

In [12]:
process_array=np.vstack((p1,p2,p3,p4,p5))

In [13]:
process_array

array([[52, 12, 81,  0, 58],
       [96,  4, 61, 16, 43],
       [38, 96, 45, 17, 58],
       [97, 21, 22, 25,  6],
       [77,  6, 19,  2, 74]])

In [14]:
# calculate the mean of each column of data
np.mean(process_array, axis=0)

array([72. , 27.8, 45.6, 12. , 47.8])

In [15]:
print("Means of Each Column of Data: ", np.mean(process_array, axis=0))

Means of Each Column of Data:  [72.  27.8 45.6 12.  47.8]
